"""empty message

Revision ID: 71bda45ce6f0
Revises: 0c6da91b3ec9
Create Date: 2020-05-24 11:37:28.861746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bda45ce6f0'
down_revision = '0c6da91b3ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notes_timestamp'), 'notes', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_timestamp'), table_name='notes')
    # ### end Alembic commands ###
